### ISSUE TITLE
Using Qt Sass 

### ISSUE THREAD

**Issue by goanpeca** [ColinDuquesnoy/QDarkStyleSheet#137]
In order to clean up definition of styles (maybe make this package more generic), we could use https://github.com/spyder-ide/qtsass so that instead of hardcoding variables within the QSS, we could define SASS variables that would be used afterwards. By doing this, we could also "on the fly" generate custom stylesheets by changing these variables (either by simple line, search and replace) or by other method.

I am suggesting this now that we need to be able to access the color variables directly from python code.

**Comment by goanpeca** [comment]
Something like:

```scss
qdarkstyle/qss/_colors.scss

// Selection
$sel_light:  #148CD2;  // (selection/hover/active)
$sel_normal: #1464A0;  // (selected)
$sel_dark:   #14506E;  // (selected disabled)

// Foreground
$for_light:  #F0F0F0;  // (texts/labels)
$for_dark:   #505F69;  // (disabled texts)

// Bacground
$bac_light:  #505F69;  // (unpressed)
$bac_normal: #32414B;  // (border, disabled, pressed, checked, toolbars, menus)
$bac_dark:   #19232D;  // (background)
```

```scss
qdarkstyle/qss/_styles.scss

/* QWidget ---------------------------------------------------------------- */

QWidget {
    background-color: $bac_dark;
    border: 0px solid $bac_normal;
    padding: 0px;
    color: $for_light;
    selection-background-color: $sel_normal;
    selection-color: $for_light;


    &:disabled {
        background-color: #19232D;
        color: #787878;
        selection-background-color: #14506E;
        selection-color: #787878;
    }

    &:item {

        &:selected {
            background-color: #1464A0;
        }

        &:hover {
            background-color: #148CD2;
            color: #32414B;
        }
    }
}
```

And then compile this file:

```scss
qdarkstyle/qss/.scss

@import 'colors';
@import 'stykes';
```
