### ISSUE TITLE
Tab corners are cut, qwidget may not have rounded borders

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#189]
Borders corners are cut

![Screenshot Linux 2019-06-13 14 40 19](https://user-images.githubusercontent.com/5084939/59454997-aebc8e80-8de9-11e9-8dc7-e8abb7e8fe5a.png)

Fixed with 

![Screenshot Linux 2019-06-13 14 39 38](https://user-images.githubusercontent.com/5084939/59455004-b3814280-8de9-11e9-8174-51d07b3b6c5e.png)

```
QTabWidget {
    padding: 2px;
    selection-background-color: $COLOR_BACKGROUND_NORMAL;

    QWidget {
        border-radius: $SIZE_BORDER_RADIUS;
    }
```

**Comment by goanpeca** [comment]
@dpizetta I think we should use a padding that is based on the border radius variable

something like

```css
QTabWidget {
    padding: $SIZE_BORDER_RADIUS/2;
    selection-background-color: $COLOR_BACKGROUND_NORMAL;

    QWidget {
        border-radius: $SIZE_BORDER_RADIUS;
    }
```
